### ISSUE TITLE
Stuck when trying to load my kdbx File

### ISSUE THREAD

**Issue by LukasKarer** [kee-org/kdbx.dart#5]
await KdbxFormat().read(kdbxFileUInt8List, Credentials.composite(
        ProtectedValue.fromString('password'), Uint8List.fromList(keyxFileUInt8List)));

This call is stuck, when i try to use it. Needed files exist, so it should be working.
Can someone of you help me guys?

**Comment by luckyrat** [comment]
Please try v0.6.0+4 in case that fixes whatever the problem was. If not, please open a new issue with a lot more information about what you're doing, with which KDBX file, and any errors/exceptions/stack traces created.
